/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_knoblul_winjfx_WinJFX */

struct TrayIconData {
  HWND hWnd;
  HMENU hMenu;
  jobject trayIconInstance;

  // для вызова коллбека в джаве (трей иконка потокобезопасная)
  JNIEnv *jni_env;
  jclass winJFX_class;
  jmethodID popupRmbCallback_methodId;
  jmethodID popupLmbCallback_methodId;
};

#ifndef _Included_ru_knoblul_winjfx_WinJFX
#define _Included_ru_knoblul_winjfx_WinJFX
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     ru_knoblul_winjfx_WinJFX
 * Method:    getWindowStyleFlags
 * Signature: (J)V
 */
JNIEXPORT jlong JNICALL Java_ru_knoblul_winjfx_WinJFX_getWindowStyleFlags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ru_knoblul_winjfx_WinJFX
 * Method:    setWindowStyleFlags
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ru_knoblul_winjfx_WinJFX_setWindowStyleFlags
  (JNIEnv *, jclass, jlong, jlong);

// /*
//  * Class:     ru_knoblul_winjfx_WinJFX
//  * Method:    bringWindowToTop
//  * Signature: (J)V
//  */
// JNIEXPORT void JNICALL Java_ru_knoblul_winjfx_WinJFX_bringWindowToTop
//   (JNIEnv *, jclass, jlong);

/*
 * Class:     ru_knoblul_winjfx_WinJFX
 * Method:    createTrayIcon
 * Signature: (Ljava/lang/Object;[B)J
 */
JNIEXPORT jlong JNICALL Java_ru_knoblul_winjfx_WinJFX_createTrayIcon
  (JNIEnv *, jclass, jobject, jbyteArray);

/*
 * Class:     ru_knoblul_winjfx_WinJFX
 * Method:    setTrayIconTooltip
 * Signature: (JLjava/lang/String)V
 */
JNIEXPORT void JNICALL Java_ru_knoblul_winjfx_WinJFX_setTrayIconTooltip
  (JNIEnv *, jclass, jlong, jstring);

  /*
 * Class:     ru_knoblul_winjfx_WinJFX
 * Method:    updateTrayIconPopupItem
 * Signature: (JIILjava/lang/String)V
 */
JNIEXPORT void JNICALL Java_ru_knoblul_winjfx_WinJFX_updateTrayIconPopupItem
  (JNIEnv *, jclass, jlong, jint, jint, jstring);

/*
 * Class:     ru_knoblul_winjfx_WinJFX
 * Method:    trayIconShowMessage
 * Signature: (JLjava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_ru_knoblul_winjfx_WinJFX_trayIconShowMessage
  (JNIEnv *, jclass, jlong, jstring, jstring, jint);

/*
 * Class:     ru_knoblul_winjfx_WinJFX
 * Method:    destroyTrayIcon
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ru_knoblul_winjfx_WinJFX_destroyTrayIcon
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ru_knoblul_winjfx_WinJFX
 * Method:    isTaskbarProgressSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ru_knoblul_winjfx_WinJFX_isTaskbarProgressSupported
  (JNIEnv *, jclass);

/*
 * Class:     ru_knoblul_winjfx_WinJFX
 * Method:    createTaskbar
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ru_knoblul_winjfx_WinJFX_createTaskbar
  (JNIEnv *, jclass);

/*
 * Class:     ru_knoblul_winjfx_WinJFX
 * Method:    setTaskbarProgressState
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_ru_knoblul_winjfx_WinJFX_setTaskbarProgressState
  (JNIEnv *, jclass, jlong, jlong, jint);
  
/*
 * Class:     ru_knoblul_winjfx_WinJFX
 * Method:    setTaskbarProgress
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_ru_knoblul_winjfx_WinJFX_setTaskbarProgress
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     ru_knoblul_winjfx_WinJFX
 * Method:    destroyTaskbar
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ru_knoblul_winjfx_WinJFX_destroyTaskbar
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
