/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Михаил' at '27.06.19 14:14' with Gradle 2.14.1
 *
 * @author Михаил, @date 27.06.19 14:14
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
